# Site settings
title: ATL Sass Meetup

description: > # this means to ignore newlines until "baseurl:"
  "A monthly gathering for Sass developers. Interested in Sass? Use it every day? Heard about it once, and want to learn more? It doesn't matter how much you know already: bring something to work on, start something new, help someone else, or just enjoy the Sassy company."

baseurl: ""

img: /assets/img

# Build settings
markdown: kramdown

exclude: ["node_modules", "gulp", "gulpfile.js", "package.json"]

permalink: /:title/
